version: "3.7"

services:
  vtiger:
    build: ./docker/php7
    ports:
      - 8080:80
    volumes:
      - ./build:/var/www/html
  mysql:
    image: javanile/mysql:5.7.28
    command: --sql-mode= --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=root
